/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.andrecordeiro;

public class App {
    public String getGreeting() {
        return "Hello world, " + System.getenv("ACM_USERNAME") + ".";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
