/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.andrecordeiro;

import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.openqa.selenium.WebDriver;

import static org.mockito.Mockito.*;

class ServiceTest {
    @Test void shouldGoToAcmLoginPage() {
        var driver = Mockito.mock(WebDriver.class);
        when(driver.getCurrentUrl()).thenReturn("https://go.oreilly.com/acm");

        new Service("user","password", driver).process();

        verify(driver, times(1)).get("https://go.oreilly.com/acm");
        verify(driver, times(1)).getCurrentUrl();
    }
}
