name: Run

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 15 1 * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "run"
  run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Clean with Gradle
      run: ./gradlew clean

    - name: Download selenium web driver for firefox
      run: curl -L https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz --output geckodriver-v0.26.0-linux64.tar.gz

    - name: Extract selenium web driver for firefox from previous download
      run: tar -xzf geckodriver-v0.26.0-linux64.tar.gz

    - name: Run with Gradle
      run: ./gradlew run -Dwebdriver.gecko.driver=geckodriver
      env:
        ACM_USERNAME: ${{ secrets.ACM_USERNAME }}
        ACM_PASSWORD: ${{ secrets.ACM_PASSWORD }}
